### ISSUE TITLE
Get java.lang.NoClassDefFoundError: com_atlassian_clover/TestNameSniffer when using a compile project reference

### ISSUE THREAD

**Issue by fbazbo** [bmuschko/gradle-clover-plugin#102] opened 2017-10-02 19:03 UTC
I have a multi-project where one of the subprojects depends on another.  Initially, I had the dependency defined like:

`compile project(":otherProject")`

but then I would get the java.lang.NoClassDefFoundError: com_atlassian_clover/TestNameSniffer for the first reference to a class in the independent project.  When I changed it to a straight repo dependency it worked fine:

`compile "com.mycompany:otherProject:${version}"`

**Comment by Alex-Vol-SV** [comment] 2017-10-02 22:18
Not sure how you get this. I have used project references which is the only way to make proper references to related projects in a multiproject configuration and have not had issues with running clover. Can you provide more details on your Gradle multi-project configuration?

**Comment by Alex-Vol-SV** [comment] 2017-10-02 22:23
The functional test example in this repository in this location uses compile project references and successfully performs clover.

[java-multi-project-with-ear](https://github.com/bmuschko/gradle-clover-plugin/tree/master/src/integTest/projects/java-multi-project-with-ear)

**Comment by Alex-Vol** [comment] 2017-10-03 04:36
Did you apply the clover plugin to all your projects including the root project? This almost seems like a mismatch between code compiled with clover and the clover library not being a dependency. Did you add the clover library dependency in the clover configuration in each project?

**Comment by fbazbo** [comment] 2017-10-03 17:00
I have the plugin specified in the root project buildscript and applied in allprojects with the clover dependency specified and configured there also.  Oddly this seems to be working now.  Must have been some cruft in some cache somewhere that was causing issue

**Comment by Alex-Vol** [comment] 2017-10-03 17:23
Closing as "not a bug"

**Closed by Alex-Vol** 2017-10-03 17:23 UTC
