### ISSUE TITLE
Update this project to use Gradle 4.x

### ISSUE THREAD

**Issue by influenza** [bmuschko/gradle-clover-plugin#106] opened 2017-12-06 02:35 UTC
In order to update the plugin to support Gradle 4.x projects, this project should be updated to use Gradle 4.x

I have started a [branch on my fork](https://github.com/influenza/gradle-clover-plugin/tree/Gradle-4.3.1) to address this but I am struggling with the classpath settings for the integration tests. Any assistance or pointers is appreciated.

**Comment by siordache** [comment] 2017-12-11 22:26
It's difficult to split the Gradle 4.x problem in two separate issues, because in both cases you have to deal with the classesDir / classesDirs problem.

To get started do the following:

- replace all occurences of `classesDir` with `classesDirs` in build.gradle.

- replace all occurrences of
`classpath files('../../../../build/classes/main')`
with
`classpath files('../../../../build/classes/java/main', '../../../../build/classes/groovy/main')`
in all gradle files under src/integTest/projects.

You can see the above changes in [this commit](https://github.com/siordache/gradle-clover-plugin/commit/68b60d5ff92191fbdd56816f5ed22d9dd4713625) on my fork.

These modifications eliminate the classpath problem, but you will still have 3 tests that fail with the error message '_Directory does not exist_'.

From this point, you can start updating the plugin to support Gradle 4.x projects. 
Thank you for taking the time to tackle this issue. I really miss this feature and I'm pretty sure I'm not the only one.

**Comment by Alex-Vol-SV** [comment] 2017-12-24 00:36
Closing as duplicate of issue #91

**Closed by Alex-Vol-SV** 2017-12-24 00:36 UTC

**Comment by Alex-Vol** [comment] 2017-12-28 19:30
FYI, I released v2.2.0 with Gradle 4.x support. Try it out and let me know how it works for you.
