### ISSUE TITLE
Grails 3 tests not executed

### ISSUE THREAD

**Issue by markandirene** [bmuschko/gradle-clover-plugin#75] opened 2016-08-15 16:43 UTC
```
dependencies {
```

:        classpath "com.bmuschko:gradle-clover-plugin:2.0.1"
    }

apply plugin: "com.bmuschko.clover"

clover  {
    additionalSourceDirs = [new File("src/main/groovy"), new File("grails-app")] as Set
    additionalTestDirs=[new File("src/test/groovy/"), new File("src/integration-test/groovy")] as Set
    includes = ['**/*.groovy', '**/_.java']
    testIncludes = ['__/_Spec.java']
    report {
        html = true
        xml = true
    }
}

grails test-app

[clover-clean] Clover Version 3.3.0, built on March 31 2014 (build-912)
[clover-clean] Loaded from: C:\Users\mxt3.gradle\caches\modules-2\files-2.1\com
.cenqua.clover\clover\3.3.0\611f5503f37cab7b57a4fe02832f0382a7a6240\clover-3.3.0
.jar
[clover-clean] Clover: Commercial License registered to Equifax Inc.
[clover-setup] Clover Version 3.3.0, built on March 31 2014 (build-912)
[clover-setup] Loaded from: C:\Users\mxt3.gradle\caches\modules-2\files-2.1\com
.cenqua.clover\clover\3.3.0\611f5503f37cab7b57a4fe02832f0382a7a6240\clover-3.3.0
.jar
[clover-setup] Clover: Commercial License registered to Equifax Inc.
[clover-setup] Clover is enabled with initstring 'C:\Users\mxt3\SME_Letter\build
/.clover/clover.db-test'
    [javac] : warning: 'includeantruntime' was not set, defaulting to build.sysc
lasspath=last; set to false for repeatable builds
    [javac] : warning: 'includeantruntime' was not set, defaulting to build.sysc
lasspath=last; set to false for repeatable builds
     [copy] Copied 2 empty directories to 2 empty directories under C:\Users\mxt
3\SME_Letter\build\classes\main
     [copy] Copied 2 empty directories to 2 empty directories under C:\Users\mxt
3\SME_Letter\build\classes\test
     [move] Moving 36 files to C:\Users\mxt3\SME_Letter\build\classes
     [move] Moved 3 empty directories to 1 empty directory under C:\Users\mxt3\S
ME_Letter\build\classes
     [move] Moving 3 files to C:\Users\mxt3\SME_Letter\build\classes
     [move] Moved 3 empty directories to 1 empty directory under C:\Users\mxt3\S
ME_Letter\build\classes
:compileIntegrationTestJava UP-TO-DATE
:compileIntegrationTestGroovy UP-TO-DATE
:processIntegrationTestResources UP-TO-DATE
:integrationTestClasses UP-TO-DATE
:integrationTest UP-TO-DATE
:mergeTestReports UP-TO-DATE
:cloverAggregateDatabases
:cloverGenerateReport UP-TO-DATE

BUILD SUCCESSFUL

None of my tests are executed and no Clover report is generated. Any ideas on what I'm doing wrong?

Thanks

Mark

**Comment by Alex-Vol** [comment] 2017-05-10 01:17
I will look for an example grails app to test this with. I do not happen to have one yet. It feels as if this is another instance of the additionalSourceDirs problem which was recently fixed.

**Comment by SergioPadilla** [comment] 2017-05-24 11:01
Hello!

I have the same issue.

`$ ./gradlew test cloverGenerateReport
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
:generateGitProperties UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava UP-TO-DATE
:compileTestGroovy UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:cloverAggregateDatabases
:cloverGenerateReport

BUILD SUCCESSFUL

Total time: 10.744 secs`

And i don't get testReport.

Hope you can help me.

Thank you in advance!

**Comment by Alex-Vol-SV** [comment] 2017-05-24 16:12
Do you have a simple Grails application that I can use to reproduce this issue? I have not been able to find a simple one to test with.

Thanks

**Comment by SergioPadilla** [comment] 2017-05-31 11:45
Hello, thank you for your response, currently I don't have a grails application open source, but I think that the problem is with the configuration. I think that the sourceDirs by default is not correct, and it doesn't looking for into grails-app directory or something like this.

I'm trying to set some properties like *includes* and *additionalSourceSets* but I get some errors. I'm going to share here to try to solve this. 

I'm trying something like this:

```
additionalSourceSets << [
            srcDirs: "grails-app"
    ]
```

but I'm getting this error:
```
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> Cannot invoke method exists() on null object
```
Setting *includes* property I don't get error, but the report is not generated

Thank you

**Comment by Alex-Vol-SV** [comment] 2017-05-31 15:50
You are providing an incomplete source set definition. 

The example in the [README.md](https://github.com/bmuschko/gradle-clover-plugin/blob/master/README.md) using the closure syntax would be like this:

```
    // Closure based syntax assuming "main" source set for the code
    additionalSourceSet {
        srcDirs = sourceSets.main.allSource.srcDirs
        classesDir = sourceSets.main.output.classesDir
    }
```

**Comment by dlehammer** [comment] 2017-06-07 06:31
Hi,

As encouraged by @Alex-Vol-SV, I've attempted to create a small vanilla Grails 3 (v3.2.0) [project](https://github.com/dlehammer/gradle-clover-plugin-issue-75), and added gradle-clover-plugin v2.1.0 (OpenClover v4.2.0) configuration based on available plugin-documentation.
(please note that Spock is the default test-framework for Grails)

The [project](https://github.com/dlehammer/gradle-clover-plugin-issue-75) demonstrates the initial symptom as described by @markandirene, ie. even though there's 2 Spock specifications present, both coverage- and test-report is empty - but no errors are reported during gradle execution...

```
> gradlew clean test cloverGenerateReport
:clean
:compileJava UP-TO-DATE
:compileGroovy
:buildProperties
:processResources
:classes
:compileTestJava UP-TO-DATE
:compileTestGroovy
:processTestResources UP-TO-DATE
:testClasses
:test
[clover-clean] OpenClover Version 4.2.0, built on April 30 2017 (build-1000)
[clover-clean] Loaded from: C:\Users\dleh\.gradle\caches\modules-2\files-2.1\org.openclover\clover\4.2.0\6e24ca61354259476c48022595355dfe022e46ca\clover-4.2.0.jar
[clover-clean] Clover free edition.
[clover-setup] OpenClover Version 4.2.0, built on April 30 2017 (build-1000)
[clover-setup] Loaded from: C:\Users\dleh\.gradle\caches\modules-2\files-2.1\org.openclover\clover\4.2.0\6e24ca61354259476c48022595355dfe022e46ca\clover-4.2.0.jar
[clover-setup] Clover free edition.
[clover-setup] Creating new database at 'C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\.clover\clover.db-test'.
[clover-setup] Clover is enabled with initstring 'C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\.clover\clover.db-test'
     [copy] Copied 2 empty directories to 2 empty directories under C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\classes\main
     [copy] Copied 2 empty directories to 2 empty directories under C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\classes\test
     [move] Moving 12 files to C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\classes
     [move] Moved 3 empty directories to 1 empty directory under C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\classes
     [move] Moving 2 files to C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\classes
     [move] Moved 3 empty directories to 1 empty directory under C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\classes
:compileIntegrationTestJava UP-TO-DATE
:compileIntegrationTestGroovy UP-TO-DATE
:processIntegrationTestResources UP-TO-DATE
:integrationTestClasses UP-TO-DATE
:integrationTest UP-TO-DATE
:mergeTestReports UP-TO-DATE
:cloverAggregateDatabases
:cloverGenerateReport

BUILD SUCCESSFUL

Total time: 7.428 secs
```
Resulting reports...
![grails_3_openclover_symptom](https://user-images.githubusercontent.com/17439718/26855776-45c31a18-4b1d-11e7-89d9-e97d0622e2ea.png)

Note; check out the [unit-test_default](https://github.com/dlehammer/gradle-clover-plugin-issue-75/releases/tag/unit-test_default) tag to verify that the 2 unit-tests are in working condition and generates a report :)

PS: I wanted to leave this comment last night to complement the [project](https://github.com/dlehammer/gradle-clover-plugin-issue-75), but was blocked by a [major service outage](https://status.github.com/messages#2017-06-07) for github :(

**Comment by Alex-Vol-SV** [comment] 2017-06-07 14:28
Thanks for the demonstration. I did something very similar using one of the working Grails examples and saw a very similar output. My observation is that the way Grails invokes the Java/Groovy compilers seems to bypass the injection of the Clover actions for instrumentation. As a result the code is not instrumented and it does not produce coverage. There may be a way to make the Clover plugin Grails aware and I will try to spend some time working out the way to do that. I understand the problem much better now and having the simpler use case you provided makes it easy to debug and further analyze. 

Thanks again for making this.

**Comment by sdelamo** [comment] 2017-06-09 13:56
One workaround that I found is to apply the Groovy plugin directly: 

`apply plugin: 'groovy'`

doing so the Groovy Compiler I can generate reports with Clover and Grails 3

**Comment by dlehammer** [comment] 2017-06-12 14:05
@sdelamo, I've tried applying the workaround you suggested to the Grails 3 project exhibiting the symptom, see branch [sdelamo_apply_plugin_groovy](https://github.com/dlehammer/gradle-clover-plugin-issue-75/tree/sdelamo_apply_plugin_groovy).
The result is currently a build failure, regardless of the groovy plugin being the first or last applied plugin. 
As far as I can tell, the problem is task overlap between the `grails-web`  and `groovy` plugins, which isn't unexpected as the `grails-web` plugin is a super-set of the `groovy` plugin.
Any further elaboration on this approach would be much appreciated.

```
> gradlew clean test cloverGenerateReport

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating root project 'gradle-clover-plugin-issue-75'.
> Failed to apply plugin [id 'org.grails.grails-web']
   > Cannot add task ':groovydoc' as a task with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by Alex-Vol-SV** [comment] 2017-06-12 15:28
I believe I understand this issue much better at this point. Grails plugin will need to be directly supported by the Clover plugin to get this working. The Clover plugin adds actions to the Groovy plugin's tasks to perform the instrument with Clover operations. Since the Grails plugin adds or replaces the Groovy plugin's tasks with Grails specific variants we will have to add conditional code to the Clover plugin to get the correct actions added to the Grails generated tasks. I am going to spend some time this week and the weekend to see if I can get a better solution for everyone.

**Comment by Alex-Vol-SV** [comment] 2017-06-12 16:56
Luckily this is not going to be a big issue. I was able to make a small targeted change and got the desired results. 

The code is currently in the [fix-issue-75-grails-code-coverage branch](https://github.com/bmuschko/gradle-clover-plugin/tree/fix-issue-75-grails-code-coverage) of this repository pending creation of integration tests. I will work out the proper integration tests and make it part of the 2.1.1 milestone release.

**Comment by Alex-Vol-SV** [comment] 2017-06-12 17:29
@dlehammer I believe the workaround suggested by @sdelamo may still work if the groovy plugin is applied before the grails plugins are applied. The Grails plugins seem to have defensive code that would allow for this configuration. But YMMV since from my brief code review of the Grails Gradle plugins they are intended to replace the Groovy plugin instead of existing side by side.

As noted above I am preparing a milestone 2.1.1 release and this fix will be included now that I fully grasp the scope of the change.

**Comment by dlehammer** [comment] 2017-06-13 07:56
@Alex-Vol-SV wrote
> @dlehammer I believe the workaround suggested by @sdelamo may still work if the groovy plugin is applied before the grails plugins are applied.

@dlehammer wrote
> The result is currently a build failure, regardless of the `groovy` plugin being the first or last applied plugin.

In the branch [sdelamo_apply_plugin_groovy](https://github.com/dlehammer/gradle-clover-plugin-issue-75/tree/sdelamo_apply_plugin_groovy) the `groovy` plugin is the first applied :-)
I suspect this may cause different results for newer versions of Grails 3, @sdelamo which Grails version have you confirmed the work-around?

@Alex-Vol-SV, I'm looking forward to v2.1.1 - I'll be happy to test a release-candidate :-)

**Comment by Alex-Vol-SV** [comment] 2017-06-13 14:29
@dlehammer I will do my best to make the remaining changes this weekend so we can have a new release soon. I cannot promise it will happen, I do have personal and paying job commitments that trump the volunteer work I do for this project.

The branch I pushed to this repo has the working code sans the required integration tests but I did prove to myself sufficiently that the changes recover the missing functionality. If you are so inclined @dlehammer you can pull this new branch and build the Clover plugin out of it to prove that it will also work in your environment. I have a few Grails example projects I can try with this change but the more coverage we get the more issues we will uncover and fix.

**Comment by sdelamo** [comment] 2017-06-13 16:19
I've  used successfully the plugin with Clover and Grails 3.2.10 and Grail 3.3.0.M2
I had an issue with integration tests which I will report differently.

**Comment by Alex-Vol-SV** [comment] 2017-06-13 17:31
I suspect the integration tests issue might be possible to address when we put together this potential fix with another pending fix I just finished. We will now have the option to leave Clover instrumented code in place to support use cases such as the integration tests. This would allow creation of instrumented JAR files for more involved use cases but it could also be the mechanism that allows integration tests to use the clover database and update coverage numbers there. If this works it may require that we configure the clover initstring as a system property in the integration tests to let Clover know the location of the database. One would also need to add the OpenClover JAR file as an optional dependency to the integration tests. These two actions could be made part of the Clover plugin if we invent a way to link the execution of the integration tests to the plugin. Today the plugin uses the Test task type as a mechanism for identifying test tasks. I believe the Grails automatic integration tests are not using this task type making the plugin ignore them.

**Comment by piotrgajow** [comment] 2017-06-24 17:31
Hi! Could you please describe briefly how to use fixed version of the plugin from the branch `fix-issue-75-grails-code-coverage` in a grails project?

**Comment by Alex-Vol-SV** [comment] 2017-06-25 17:39
You would need to do a locally hosted build of the plugin from that branch. Nothing changes in the way the plugin works. It just recognizes the Grails plugins which act as surrogates for the Groovy build plugin.
You would need to publish the plugin locally and reference it using a private build version.

I have been busy with day job and family to finish the integration. I hope to put some time on this today and have the 2.1.1 milestone released this week.

**Comment by piotrgajow** [comment] 2017-06-25 18:02
That would be great!
Thank you

**Comment by sgates** [comment] 2017-06-26 12:38
Cool thanks Alex, looking forward to it!

**Closed** 2017-06-27 23:26 UTC
Labels: Feature Request, Fixed

**Comment by dlehammer** [comment] 2017-06-29 13:05
@Alex-Vol-SV congratulations with the v2.1.1 release!
I've verified the fix and updated the symptom [project ](https://github.com/dlehammer/gradle-clover-plugin-issue-75) accordingly.

```
> gradlew clean test cloverGenerateReport
:clean
:compileJava UP-TO-DATE
:compileGroovy
:buildProperties
:processResources
:classes
:compileTestJava UP-TO-DATE
:compileTestGroovy
:processTestResources UP-TO-DATE
:testClasses
:test
[clover-clean] OpenClover Version 4.2.0, built on April 30 2017 (build-1000)
[clover-clean] Loaded from: C:\Users\dleh\.gradle\caches\modules-2\files-2.1\org.openclover\clover\4.2.0\6e24ca61354259476c48022595355dfe022e46ca\clover-4.2.0.jar
[clover-clean] Clover free edition.
[clover-setup] OpenClover Version 4.2.0, built on April 30 2017 (build-1000)
[clover-setup] Loaded from: C:\Users\dleh\.gradle\caches\modules-2\files-2.1\org.openclover\clover\4.2.0\6e24ca61354259476c48022595355dfe022e46ca\clover-4.2.0.jar
[clover-setup] Clover free edition.
[clover-setup] Creating new database at 'C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\.clover\clover.db-test'.
[clover-setup] Clover is enabled with initstring 'C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\.clover\clover.db-test'
[clover-setup] Detected groovyc compiler groovyc=org.codehaus.groovy.ant.Groovyc
  [groovyc] Compiling 5 source files to C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\classes\main
[clover-setup] Updating existing database at 'C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\.clover\clover.db-test'.
  [groovyc] Compiling 2 source files to C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\classes\test
[clover-setup] Updating existing database at 'C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\.clover\clover.db-test'.
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1g; support was removed in 8.0
                                                                                                           [move] Moving 12 files to C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\classesuilding 52% > :test
     [move] Moved 3 empty directories to 1 empty directory under C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\classes
     [move] Moving 2 files to C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\classes
     [move] Moved 3 empty directories to 1 empty directory under C:\Users\dleh\work\tmp\3.2.0\gradle-clover-plugin-issue-75\build\classes
:compileIntegrationTestJava UP-TO-DATE
:compileIntegrationTestGroovy UP-TO-DATE
:processIntegrationTestResources UP-TO-DATE
:integrationTestClasses UP-TO-DATE
:integrationTest UP-TO-DATE
:mergeTestReports
:cloverAggregateDatabases
:cloverGenerateReport

BUILD SUCCESSFUL

Total time: 16.882 secs
```
Resulting reports...
![gradle-clover-plugin-issue-75_fix_applied_reports](https://user-images.githubusercontent.com/17439718/27688737-fcef7f04-5cdb-11e7-987b-cae1be79b083.png)

Only hiccup is: 
> No test results could be found. Please ensure that you have instrumented your unit tests correctly.

Is this a configuration issue?

**Comment by Alex-Vol** [comment] 2017-06-29 16:16
Yes, this is a known Clover issue with tests using the newer JUnit rules facilities. The configuration supports this correctly if you set the clover closure properties `testResultsDir` and `testResultsInclude` as seen in the grails project used for integration tests.
[build.gradle testResults settings](https://github.com/bmuschko/gradle-clover-plugin/blob/master/src/integTest/projects/grails-project/build.gradle#L108)

If your project contains multiple test tasks you must use the TestReport task to consolidate the results from all tests into a single report. The reference will help with such a configuration [Create Test Report in Root Project](https://github.com/kercheval/GradleCMPlugin/wiki/Create-Test-Report-in-Root-Project-with-Gradle)

**Comment by dlehammer** [comment] 2017-06-30 12:48
@Alex-Vol thanks for replying, , the suggested `clover.report` [block](https://github.com/dlehammer/gradle-clover-plugin-issue-75/blob/b9e4b5203d38257fb3906cde5a04e3c472214d48/build.gradle#L130) was already identical to your example, the [fix](https://github.com/dlehammer/gradle-clover-plugin-issue-75/commit/75e9cb833452c003a7d16145fa8a2807371cb42c) was changing the `clover.testIncludes ` value :-)

![fix](https://user-images.githubusercontent.com/17439718/27735908-1f4f6156-5da2-11e7-83dd-11c8eae75bb9.png)

Resulting Clover report:
![report](https://user-images.githubusercontent.com/17439718/27735978-68462df4-5da2-11e7-8dcb-c1bab6260d94.png)

**Comment by Alex-Vol** [comment] 2017-06-30 17:50
Perhaps it is time to add a default **/*Spec.groovy to the plugin testIncludes. It is using **/*Test.groovy for the default. I will add a feature request to make it have both so it is backwards compatible.

**Comment by davidsonnabend** [comment] 2017-11-17 15:02
Sorry that I comment an already closed issue but I think that it is the best place.

I managed to run the plugin with grails 3.3.0.
In the clover report I just see the test results of my unit tests, the integration tests are not listed.
The coverage looks good - the integration tests are evaluated. As mentioned by @Alex-Vol I tried to merge the test results, so that clover just needs to read one folder.

I created a gradle task which will copy the `TEST-*.xml` files of the integration test into the unit test folder.  This happens before `cloverAggregateDatabases` and `cloverGenerateReport` starts running. The clover report won't show the integration test results.

What can I try to see my integration test results in the clover report?

**Comment by Alex-Vol** [comment] 2017-11-17 21:05
The way this plugin deals with multiple source sets and additional test tasks is by using the configuration options for `additionalSourceSets`, `additionalTestSourceSets` and `includeTasks`.

See the documentation regarding these in the README.md.

An example of a project with integration tests and the expected usage of these configuration stanzas is here: [java-project-with-additional-tests](https://github.com/bmuschko/gradle-clover-plugin/blob/master/src/integTest/projects/java-project-with-additional-tests/build.gradle#L50)

**Comment by davidsonnabend** [comment] 2017-11-18 00:12
I alreade saw that part of the README but failed to configure it right and tried another approach to solve my issue.  With your hint that `additionalTestSourceSets`is the way to go I finnally found the solution. My fault was that I was using one of the default variables so that the files where searched within  `integrationTest` folder instead of the default grails folder:`integration-test`.

Thanks for your help!

**Comment by andersaaberg** [comment] 2019-11-06 15:46
Thanks to @davidsonnabend for solving the problem with missing integrationtest results in the clover report (based on the java example: https://github.com/bmuschko/gradle-clover-plugin/blob/master/src/functTest/projects/java-project-with-additional-tests/build.gradle).

Here is a complete solution for Grails that also takes care of filtering the non-exsiting srcDir:
```
        clover {
            additionalTestSourceSet {
                srcDirs = sourceSets.integrationTest.groovy.srcDirs.findAll { !it.path.contains('integrationTest')}
                classesDir = sourceSets.integrationTest.groovy.outputDir
            }
        }
```

You can also just create an empty `/path/to/project/src/integrationTest/groovy` folder instead, but instead I prefer to filter the sourcesets to avoid adding unused directories.
