### ISSUE TITLE
Error running cloveraggregateReports 

### ISSUE THREAD

**Issue by alfrye** [bmuschko/gradle-clover-plugin#104] opened 2017-10-31 12:26 UTC
I have a gradle multi project java project and when run cloverAggregateReports I am getting the following messsage: 
"Task 'cloverAggregateReports' not found in root project '"

Do I need to specify the task in my root project?

The plugin is creating a reports for each of my subprojects but I would like an aggregate report. 
I have this setup in my build.gradle 

`allprojects {
 	apply plugin: "com.jfrog.artifactory"
 	apply plugin: "com.bmuschko.clover"
 	apply plugin: 'groovy'
 	dependencies {
 	clover 'org.openclover:clover:4.2.0'
 	}
}
 	`

**Comment by Alex-Vol** [comment] 2017-10-31 18:38
I suspect the plugin was not properly applied or configured on the root project. Although you seem to use the allprojects iteration to apply it. It works fine on all my projects when I apply it correctly.

Are you specifying the allprojects iteration in the root project's build.gradle?

**Comment by Alex-Vol** [comment] 2017-11-17 21:09
I am inclined to close this as "User error", I cannot reproduce this in any way. Feel free to attach more information or a way that you can make this happen to have me research further.

**Closed by Alex-Vol** 2017-11-17 21:09 UTC
