### ISSUE TITLE
cloverAggregateDatabases is not working 

### ISSUE THREAD

**Issue by ravichandrakn** [bmuschko/gradle-clover-plugin#101] opened 2017-09-21 06:50 UTC
HI, I have project, which contains multiple sub-projects, each sub-project has source set and test set, clover is able to instrument classes with individual sub-project and generate code coverage within the same sub-project, problem here is my 90% test cases i have written in one particular sub-project, gradle is having reference to other sub-projects. While generating code coverage for whole project, i'm observing that my code coverage is completely wrong(comparing against intelliji clover plugin).  I was thinking that gradle-clover-plugin is not working as expected, how do i fix this issue? 

1. how do i pass each sub-projects clover.db files to each sub-projects?
2. Any other alternatives suggestions would be welcomed. 

here is log: i do have multitple .db file, but its not picking up to merge. what parameters i need to mention, so that i can pick up the other .db files.
[ant:clover-merge] Merging database 1 of 1: /Users/user/workspace/projectb/projectb-test/build/.clover/clover.db-test

**Comment by ravichandrakn** [comment] 2017-09-21 06:52
example: 

project {
  project A {
    source set
    test set(having minimal tests)
  }
  project B {
    source set
    test set(having minimal tests)
  }
  project C {
    source set
    test set(maxinum test cases resides here)
  }
}

**Comment by Alex-Vol-SV** [comment] 2017-09-23 04:49
The `cloverAggregateReports` task is used to correctly merge and report on multi-project configurations. However, you are looking for indirect code coverage which may not work because of the way the plugin instruments the code just in time to run unit tests. One option that may give you better results is to try passing the property `-PcloverInstrumentedJar=true` on the command line. This will allow the classes from projectA and projectB to be left in instrumented state. That should generate the coverage recordings you are looking.

I tried the above but I am not getting the extra coverage in a test project so this may not work either. I tend to avoid indirect code coverage in my projects, I always make the unit tests closest to the unit under test provide the needed coverage.

**Comment by Alex-Vol-SV** [comment] 2017-09-23 04:51
For what it is worth, in my experiments the `cloverAggregateReports` task correctly shows multiple databases getting merged and the aggregate report shows all relevant coverage from each project in one report.

**Comment by Alex-Vol** [comment] 2017-10-03 17:26
I do not consider testing indirectly or in a different module from the one the code is building from a good practice. This works as intended when direct testing is applied which always gives the best kind of coverage. I am closing as "won't fix" since I find this is not a desirable feature.

**Closed by Alex-Vol** 2017-10-03 17:26 UTC
